"use client";

import {FormEvent, useEffect, useState} from "react";
import {createUserWithEmailAndPassword,GoogleAuthProvider,onAuthStateChanged,sendEmailVerification,sendPasswordResetEmail,signInWithEmailAndPassword,signInWithPopup,updateProfile} from "firebase/auth";
import {auth} from "./firebase";
import {recordLogin} from "./activity";

type Mode="login"|"signup"|"forgot";
const labels={
 mr:{brand:"श्री गुरुपीठ",tag:"दिंडोरी प्रणीत सेवा मार्ग",login:"लॉग इन",signup:"नवीन खाते तयार करा",forgot:"पासवर्ड रीसेट करा",intro:"सेवा, साधना आणि वाचनाचा प्रवास सुरू ठेवा.",name:"पूर्ण नाव",email:"ईमेल",password:"पासवर्ड",confirm:"पासवर्ड पुन्हा लिहा",google:"Google सह सुरू ठेवा",or:"किंवा",reset:"रीसेट लिंक पाठवा",noAccount:"खाते नाही?",hasAccount:"आधीच खाते आहे?",forgotLink:"पासवर्ड विसरलात?",back:"लॉग इनवर परत जा",working:"कृपया थांबा…",mismatch:"दोन्ही पासवर्ड समान असणे आवश्यक आहे.",verify:"खाते तयार झाले. सत्यापन लिंक ईमेलवर पाठवली आहे.",sent:"पासवर्ड रीसेट लिंक ईमेलवर पाठवली आहे.",theme:"थीम",language:"English"},
 en:{brand:"Shri Gurupeeth",tag:"Dindori Pranit Seva Marg",login:"Log in",signup:"Create account",forgot:"Reset password",intro:"Continue your seva, sadhana and reading journey.",name:"Full name",email:"Email",password:"Password",confirm:"Confirm password",google:"Continue with Google",or:"or",reset:"Send reset link",noAccount:"New here?",hasAccount:"Already have an account?",forgotLink:"Forgot password?",back:"Back to login",working:"Please wait…",mismatch:"Both passwords must match.",verify:"Account created. A verification link was sent to your email.",sent:"A password reset link was sent to your email.",theme:"Theme",language:"मराठी"}
};
function errorText(error:unknown,lang:"mr"|"en"){
 const code=typeof error==="object"&&error&&"code" in error?String((error as {code:string}).code):"";
 const messages:Record<string,[string,string]>={"auth/invalid-credential":["ईमेल किंवा पासवर्ड चुकीचा आहे.","Incorrect email or password."],"auth/email-already-in-use":["या ईमेलवर खाते आधीच आहे.","An account already exists for this email."],"auth/invalid-email":["योग्य ईमेल लिहा.","Enter a valid email."],"auth/weak-password":["पासवर्ड किमान ६ अक्षरांचा असावा.","Password must be at least 6 characters."],"auth/popup-closed-by-user":["Google लॉग इन पूर्ण झाले नाही.","Google sign-in was not completed."],"auth/too-many-requests":["खूप प्रयत्न झाले. थोड्या वेळाने पुन्हा प्रयत्न करा.","Too many attempts. Try again later."]};
 return messages[code]?.[lang==="mr"?0:1]||(lang==="mr"?"काहीतरी चूक झाली. पुन्हा प्रयत्न करा.":"Something went wrong. Please try again.");
}
export default function AuthPage({mode}:{mode:Mode}){
 const [lang,setLang]=useState<"mr"|"en">("mr"),[theme,setTheme]=useState<"light"|"dark">("light"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const l=labels[lang];
 useEffect(()=>{const savedLang=localStorage.getItem("gurupeeth-language");const savedTheme=localStorage.getItem("gurupeeth-theme");if(savedLang==="mr"||savedLang==="en")setLang(savedLang);if(savedTheme==="light"||savedTheme==="dark")setTheme(savedTheme);return onAuthStateChanged(auth,user=>{if(user)window.location.replace("/")})},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.lang=lang;localStorage.setItem("gurupeeth-language",lang);localStorage.setItem("gurupeeth-theme",theme)},[lang,theme]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");if(mode==="signup"&&password!==confirm){setError(l.mismatch);return}setBusy(true);try{if(mode==="login"){const result=await signInWithEmailAndPassword(auth,email.trim(),password);recordLogin(result.user).catch(()=>{})}else if(mode==="signup"){const result=await createUserWithEmailAndPassword(auth,email.trim(),password);if(name.trim())await updateProfile(result.user,{displayName:name.trim()});recordLogin(result.user).catch(()=>{});await sendEmailVerification(result.user,{url:window.location.origin});setMessage(l.verify)}else{await sendPasswordResetEmail(auth,email.trim(),{url:window.location.origin+"/login"});setMessage(l.sent)}}catch(e){setError(errorText(e,lang))}finally{setBusy(false)}}
 async function google(){setBusy(true);setError("");try{const result=await signInWithPopup(auth,new GoogleAuthProvider());recordLogin(result.user).catch(()=>{})}catch(e){setError(errorText(e,lang));setBusy(false)}}
 return <main className="auth-page"><header className="auth-page-header"><a href="/login" className="auth-page-brand"><img src="/app-assets/guru-app-icon.png" alt=""/><span><b>{l.brand}</b><small>{l.tag}</small></span></a><div><button onClick={()=>setTheme(theme==="light"?"dark":"light")} aria-label={l.theme}>{theme==="light"?"☾":"☀"}</button><button onClick={()=>setLang(lang==="mr"?"en":"mr")}>{l.language}</button></div></header><div className="auth-page-layout"><section className="auth-page-welcome"><span>॥ श्री स्वामी समर्थ ॥</span><h1>{lang==="mr"?"सेवा, साधना आणि संस्कारांचा मार्ग":"A path of seva, sadhana and values"}</h1><p>{l.intro}</p><img src="/app-assets/swami_samarth.png" alt="श्री स्वामी समर्थ"/></section><section className="auth-page-card"><div className="auth-card-mark"><img src="/app-assets/guru-app-icon.png" alt=""/></div><h2>{mode==="login"?l.login:mode==="signup"?l.signup:l.forgot}</h2><p>{l.intro}</p>{mode!=="forgot"&&<><button className="auth-google" onClick={google} disabled={busy}><b>G</b>{l.google}</button><div className="auth-divider"><span>{l.or}</span></div></>}<form onSubmit={submit}>{mode==="signup"&&<label>{l.name}<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label>}<label>{l.email}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label>{mode!=="forgot"&&<><label>{l.password}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} autoComplete={mode==="signup"?"new-password":"current-password"} required/></label>{mode==="signup"&&<label>{l.confirm}<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={6} autoComplete="new-password" required/></label>}</>}{error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="auth-success" role="status">{message}</p>}<button className="auth-primary" disabled={busy}>{busy?l.working:mode==="login"?l.login:mode==="signup"?l.signup:l.reset}</button></form><div className="auth-page-links">{mode==="login"&&<><a href="/forgot-password">{l.forgotLink}</a><span>{l.noAccount} <a href="/signup">{l.signup}</a></span></>}{mode==="signup"&&<span>{l.hasAccount} <a href="/login">{l.login}</a></span>}{mode==="forgot"&&<a href="/login">← {l.back}</a>}</div></section></div></main>;
}
