"use client";
import Image from "next/image";
import {useEffect,useState} from "react";
type Entry={title:string;text:string};
const services=[
 {id:"nitya",title:"à¤¨à¤¿à¤¤à¥à¤¯à¤¸à¥‡à¤µà¤¾",sub:"à¥§à¥ª à¤¸à¥à¤¤à¥‹à¤¤à¥à¤° à¤µ à¤®à¤‚à¤¤à¥à¤°",img:"new_nitya_seva.png"},{id:"aarti",title:"à¤†à¤°à¤¤à¥€ à¤¸à¤‚à¤—à¥à¤°à¤¹",sub:"à¤¦à¥ˆà¤¨à¤¿à¤• à¤†à¤°à¤¤à¥€",img:"new_arti_sangrah.png"},
 {id:"charitra",title:"à¤¸à¥à¤µà¤¾à¤®à¥€ à¤šà¤°à¤¿à¤¤à¥à¤°",sub:"à¥¨à¥§ à¤…à¤§à¥à¤¯à¤¾à¤¯",img:"new_swamicharitra.png"},{id:"jap",title:"à¤®à¤‚à¤¤à¥à¤°à¤œà¤ª",sub:"à¤œà¤ª à¤®à¥‹à¤œà¤£à¥€",img:"new_mantra_jap.png"},
 {id:"chandi",title:"à¤…à¤­à¥à¤¯à¤œà¤¾ à¤šà¤‚à¤¡à¥€",sub:"à¤¸à¥‡à¤µà¤¾ à¤µ à¤®à¤¾à¤¹à¤¿à¤¤à¥€",img:"new_abjya_chandi.png"},{id:"guide",title:"à¤®à¤¾à¤°à¥à¤—à¤¦à¤°à¥à¤¶à¤¿à¤•à¤¾",sub:"à¤ªà¤‚à¤šà¤¾à¤‚à¤— à¤µ à¤®à¥à¤¹à¥‚à¤°à¥à¤¤",img:"new_margadarshika.png"},
 {id:"festivals",title:"à¤¸à¤£-à¤µà¤¾à¤°",sub:"à¤‰à¤¤à¥à¤¸à¤µ à¤¦à¤¿à¤¨à¤¦à¤°à¥à¤¶à¤¿à¤•à¤¾",img:"new_san_var.png"},{id:"myseva",title:"à¤®à¤¾à¤à¥€ à¤¸à¥‡à¤µà¤¾",sub:"à¤¸à¥‡à¤µà¤¾ à¤¨à¥‹à¤‚à¤¦",img:"new_majhi_seva.png"}
];
const centers=[["à¤¶à¥à¤°à¥€ à¤—à¥à¤°à¥à¤ªà¥€à¤ ","cardgurupeeth.png"],["à¤¶à¥à¤°à¥€ à¤ªà¥à¤°à¤¸à¤¾à¤¦à¤¾à¤²à¤¯","cardprasadalay.png"],["à¤†à¤¯à¥à¤°à¥à¤µà¥‡à¤¦à¤¿à¤• à¤¹à¥‰à¤¸à¥à¤ªà¤¿à¤Ÿà¤²","cardayuhospital.png"]];
const remoteInfo:Record<string,{title:string;intro:string;items:string[]}>= {
 aarti:{title:"à¤†à¤°à¤¤à¥€ à¤¸à¤‚à¤—à¥à¤°à¤¹",intro:"à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥ à¤¸à¥‡à¤µà¤¾ à¤®à¤¾à¤°à¥à¤—à¤¾à¤¤à¥€à¤² à¤¦à¥ˆà¤¨à¤¿à¤• à¤†à¤°à¤¤à¥€ à¤¸à¤‚à¤—à¥à¤°à¤¹.",items:["à¤¶à¥à¤°à¥€ à¤—à¤£à¤ªà¤¤à¥€ à¤†à¤°à¤¤à¥€","à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥ à¤†à¤°à¤¤à¥€","à¤¶à¥à¤°à¥€ à¤¦à¤¤à¥à¤¤ à¤†à¤°à¤¤à¥€","à¤¶à¥à¤°à¥€ à¤¦à¥à¤°à¥à¤—à¤¾ à¤¦à¥‡à¤µà¥€ à¤†à¤°à¤¤à¥€"]},
 chandi:{title:"à¤…à¤­à¥à¤¯à¤œà¤¾ à¤šà¤‚à¤¡à¥€ à¤¸à¥‡à¤µà¤¾",intro:"à¤…à¤­à¥à¤¯à¤œà¤¾ à¤šà¤‚à¤¡à¥€ à¤¸à¥‡à¤µà¥‡à¤šà¥€ à¤®à¤¾à¤¹à¤¿à¤¤à¥€, à¤¨à¤¿à¤¯à¤® à¤µ à¤¸à¥‡à¤µà¤¾ à¤•à¥à¤°à¤®.",items:["à¤¸à¥‡à¤µà¤¾ à¤ªà¤°à¤¿à¤šà¤¯","à¤¸à¥‡à¤µà¤¾ à¤¸à¤‚à¤•à¤²à¥à¤ª","à¤ªà¤¾à¤  à¤•à¥à¤°à¤®","à¤¸à¥‡à¤µà¤¾ à¤¸à¤®à¤°à¥à¤ªà¤£"]},
 guide:{title:"à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥ à¤®à¤¾à¤°à¥à¤—à¤¦à¤°à¥à¤¶à¤¿à¤•à¤¾",intro:"à¤ªà¤‚à¤šà¤¾à¤‚à¤—, à¤°à¤¾à¤¹à¥‚ à¤•à¤¾à¤³, à¤¶à¥à¤­à¤¾à¤¶à¥à¤­ à¤•à¥‹à¤·à¥à¤Ÿà¤•, à¤®à¥à¤¹à¥‚à¤°à¥à¤¤ à¤†à¤£à¤¿ à¤¸à¥à¤µà¤¿à¤šà¤¾à¤°.",items:["à¤†à¤œà¤šà¥‡ à¤ªà¤‚à¤šà¤¾à¤‚à¤—","à¤°à¤¾à¤¹à¥‚ à¤•à¤¾à¤³","à¤¶à¥à¤­à¤¾à¤¶à¥à¤­ à¤•à¥‹à¤·à¥à¤Ÿà¤•","à¤®à¥à¤¹à¥‚à¤°à¥à¤¤","à¤¸à¥à¤µà¤¿à¤šà¤¾à¤°"]},
 festivals:{title:"à¤¸à¤£-à¤µà¤¾à¤° à¤µ à¤‰à¤¤à¥à¤¸à¤µ",intro:"à¤¦à¤¿à¤‚à¤¡à¥‹à¤°à¥€ à¤ªà¥à¤°à¤£à¥€à¤¤ à¤‰à¤¤à¥à¤¸à¤µ à¤†à¤£à¤¿ à¤­à¤¾à¤°à¤¤à¥€à¤¯ à¤¸à¤£à¤¾à¤‚à¤šà¥€ à¤¦à¤¿à¤¨à¤¦à¤°à¥à¤¶à¤¿à¤•à¤¾.",items:["à¤®à¤¾à¤¸à¤¿à¤• à¤‰à¤¤à¥à¤¸à¤µ","à¤—à¥à¤°à¥à¤ªà¥€à¤  à¤‰à¤¤à¥à¤¸à¤µ","à¤¸à¤£ à¤µ à¤µà¤¿à¤¶à¥‡à¤· à¤¦à¤¿à¤µà¤¸"]},
 myseva:{title:"à¤®à¤¾à¤à¥€ à¤¸à¥‡à¤µà¤¾",intro:"à¤†à¤ªà¤²à¥€ à¤¦à¥ˆà¤¨à¤¿à¤• à¤µ à¤®à¤¾à¤¸à¤¿à¤• à¤¸à¥‡à¤µà¤¾ à¤¨à¥‹à¤‚à¤¦ à¤¯à¥‡à¤¥à¥‡ à¤µà¥à¤¯à¤µà¤¸à¥à¤¥à¤¾à¤ªà¤¿à¤¤ à¤•à¤°à¤¾.",items:["à¤¦à¥ˆà¤¨à¤¿à¤• à¤¸à¥‡à¤µà¤¾","à¤¸à¤¾à¤ªà¥à¤¤à¤¾à¤¹à¤¿à¤• à¤¸à¥‡à¤µà¤¾","à¤®à¤¾à¤¸à¤¿à¤• à¤¸à¥‡à¤µà¤¾"]}
};
function cleanHtml(value:string){return value.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ").trim()}
export default function Home(){
 const [view,setView]=useState("home"),[entries,setEntries]=useState<Entry[]>([]),[selected,setSelected]=useState<Entry|null>(null),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[count,setCount]=useState(0);
 useEffect(()=>{
  if(view!=="nitya"&&view!=="charitra") return;
  setLoading(true); setEntries([]); setSelected(null);
  const file=view==="nitya"?"nityasevastotramantra.json":"newswamicharitra.json";
  fetch(`/app-assets/${file}`)
   .then(r=>{if(!r.ok) throw Error(); return r.json()})
   .then(data=>{
    const next:Entry[]=view==="nitya"
     ? data.resources.string.map((x:{_name:string,__text:string})=>({title:x._name,text:x.__text}))
     : data.data.map((x:{title:string,description:string})=>({title:x.title,text:cleanHtml(x.description)}));
    setEntries(next);
   })
   .finally(()=>setLoading(false));
 },[view]);
 function openService(id:string){if(id==="jap")setOpen(true);else setView(id)}
 const info=remoteInfo[view];
 return <main className="shell">
  <header><button aria-label="Menu">â˜°</button><div className="brand"><Image unoptimized src="/app-assets/ic_launcher.png" alt="" width={42} height={42}/><div><b>à¤¶à¥à¤°à¥€ à¤—à¥à¤°à¥à¤ªà¥€à¤ </b><small>à¤¦à¤¿à¤‚à¤¡à¥‹à¤°à¥€ à¤ªà¥à¤°à¤£à¥€à¤¤ à¤¸à¥‡à¤µà¤¾ à¤®à¤¾à¤°à¥à¤—</small></div></div><button className="lang">à¤®à¤°à¤¾à¤ à¥€âŒ„</button></header>
  {view==="home"&&<><section className="hero"><div><em>à¥¥ à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥ à¥¥</em><h1>à¤¸à¥‡à¤µà¤¾, à¤¸à¤¾à¤§à¤¨à¤¾ à¤†à¤£à¤¿<br/>à¤¸à¤‚à¤¸à¥à¤•à¤¾à¤°à¤¾à¤‚à¤šà¤¾ à¤®à¤¾à¤°à¥à¤—</h1><p>à¤¨à¤¿à¤¤à¥à¤¯à¤¸à¥‡à¤µà¤¾, à¤†à¤°à¤¤à¥€, à¤®à¤‚à¤¤à¥à¤°à¤œà¤ª à¤†à¤£à¤¿ à¤¸à¥‡à¤µà¤¾ à¤®à¤¾à¤°à¥à¤—à¤¾à¤šà¥€ à¤®à¤¾à¤¹à¤¿à¤¤à¥€ à¤†à¤¤à¤¾ à¤à¤•à¤¾ à¤ à¤¿à¤•à¤¾à¤£à¥€.</p><button className="primary" onClick={()=>setView("nitya")}>à¤†à¤œà¤šà¥€ à¤¨à¤¿à¤¤à¥à¤¯à¤¸à¥‡à¤µà¤¾ â†’</button></div><div className="portrait"><i/><Image unoptimized src="/app-assets/swami_samarth.png" alt="à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥" width={340} height={340} priority/></div></section><section className="content"><div className="heading"><div><em>à¤†à¤ªà¤²à¥€ à¤¦à¥ˆà¤¨à¤¿à¤• à¤¸à¥‡à¤µà¤¾</em><h2>à¤¸à¥‡à¤µà¤¾ à¤¸à¥à¤µà¤¿à¤§à¤¾</h2></div></div><div className="grid">{services.map(x=><button className="card" key={x.id} onClick={()=>openService(x.id)}><span><Image unoptimized src={`/app-assets/${x.img}`} alt="" width={52} height={52}/></span><b>{x.title}</b><small>{x.sub}</small></button>)}</div></section><section className="quote">â€œ<p>à¤­à¤¿à¤Š à¤¨à¤•à¥‹à¤¸, à¤®à¥€ à¤¤à¥à¤à¥à¤¯à¤¾ à¤ªà¤¾à¤ à¥€à¤¶à¥€ à¤†à¤¹à¥‡.</p><small>â€” à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥</small></section><section className="content"><div className="heading"><div><em>à¤¸à¥‡à¤µà¤¾ à¤•à¤¾à¤°à¥à¤¯</em><h2>à¤†à¤ªà¤²à¥€ à¤•à¥‡à¤‚à¤¦à¥à¤°à¥‡</h2></div></div><div className="centers">{centers.map(([t,img])=><article key={t}><Image unoptimized src={`/app-assets/${img}`} alt={t} fill/><div><b>{t}</b><small>à¤®à¤¾à¤¹à¤¿à¤¤à¥€ à¤ªà¤¹à¤¾ â†’</small></div></article>)}</div></section></>}
  {(view==="nitya"||view==="charitra")&&<section className="page reader-page"><button className="back" onClick={()=>selected?setSelected(null):setView("home")}>â† {selected?"à¤¸à¥‚à¤šà¥€":"à¤®à¥à¤–à¥à¤¯à¤ªà¥ƒà¤·à¥à¤ "}</button><em>{view==="nitya"?"à¤¦à¥ˆà¤¨à¤¿à¤• à¤‰à¤ªà¤¾à¤¸à¤¨à¤¾":"à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤šà¤°à¤¿à¤¤à¥à¤° à¤¸à¤¾à¤°à¤¾à¤®à¥ƒà¤¤"}</em><h2>{selected?.title||(view==="nitya"?"à¤¨à¤¿à¤¤à¥à¤¯à¤¸à¥‡à¤µà¤¾ à¤¸à¥à¤¤à¥‹à¤¤à¥à¤° à¤µ à¤®à¤‚à¤¤à¥à¤°":"à¤¸à¥à¤µà¤¾à¤®à¥€ à¤šà¤°à¤¿à¤¤à¥à¤°")}</h2>{selected?<article className="devotional-text">{selected.text}</article>:loading?<div className="loading">à¤…à¤§à¤¿à¤•à¥ƒà¤¤ à¤®à¤œà¤•à¥‚à¤° à¤‰à¤˜à¤¡à¤¤ à¤†à¤¹à¥‡â€¦</div>:<div className="list">{entries.map((x,i)=><button key={x.title} onClick={()=>setSelected(x)}><span>{String(i+1).padStart(2,"0")}</span><b>{x.title}</b><strong>â€º</strong></button>)}</div>}</section>}
  {info&&<section className="page"><button className="back" onClick={()=>setView("home")}>â† à¤®à¥à¤–à¥à¤¯à¤ªà¥ƒà¤·à¥à¤ </button><em>à¤¶à¥à¤°à¥€ à¤—à¥à¤°à¥à¤ªà¥€à¤ </em><h2>{info.title}</h2><p>{info.intro}</p><div className="list">{info.items.map((x,i)=><button key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><strong>â€º</strong></button>)}</div><p className="source-note">à¤¯à¤¾ à¤µà¤¿à¤­à¤¾à¤—à¤¾à¤šà¤¾ à¤¸à¤µà¤¿à¤¸à¥à¤¤à¤° à¤®à¤œà¤•à¥‚à¤° à¤®à¥‚à¤³ à¥²à¤ªà¤®à¤§à¥à¤¯à¥‡ à¤‘à¤¨à¤²à¤¾à¤‡à¤¨ à¤¸à¤°à¥à¤µà¥à¤¹à¤°à¤µà¤°à¥‚à¤¨ à¤¯à¥‡à¤¤à¥‹. APK à¤®à¤§à¥à¤¯à¥‡ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¸à¤²à¥‡à¤²à¥€ à¤®à¤¾à¤¹à¤¿à¤¤à¥€ à¤…à¤‚à¤¦à¤¾à¤œà¤¾à¤¨à¥‡ à¤¦à¤¾à¤–à¤µà¤²à¥‡à¤²à¥€ à¤¨à¤¾à¤¹à¥€.</p></section>}
  {view==="calendar"&&<section className="page"><button className="back" onClick={()=>setView("home")}>â† à¤®à¥à¤–à¥à¤¯à¤ªà¥ƒà¤·à¥à¤ </button><em>à¤ªà¤‚à¤šà¤¾à¤‚à¤—</em><h2>à¤†à¤œà¤šà¤¾ à¤¦à¤¿à¤µà¤¸</h2><div className="date"><small>à¤¸à¥‹à¤®à¤µà¤¾à¤°</small><b>à¥§à¥©</b><span>à¤œà¥à¤²à¥ˆ à¥¨à¥¦à¥¨à¥¬</span><hr/><p>à¤†à¤·à¤¾à¤¢ à¤•à¥ƒà¤·à¥à¤£ à¤¤à¥à¤°à¤¯à¥‹à¤¦à¤¶à¥€</p></div></section>}
  {view==="about"&&<section className="page"><button className="back" onClick={()=>setView("home")}>â† à¤®à¥à¤–à¥à¤¯à¤ªà¥ƒà¤·à¥à¤ </button><em>à¤¸à¥‡à¤µà¤¾ à¤®à¤¾à¤°à¥à¤—</em><h2>à¤¶à¥à¤°à¥€ à¤—à¥à¤°à¥à¤ªà¥€à¤  à¤µà¤¿à¤·à¤¯à¥€</h2><Image unoptimized className="about" src="/app-assets/card_dindoripranit.png" alt="à¤¸à¥‡à¤µà¤¾ à¤®à¤¾à¤°à¥à¤—" width={700} height={250}/><p>à¤¦à¤¿à¤‚à¤¡à¥‹à¤°à¥€ à¤ªà¥à¤°à¤£à¥€à¤¤ à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥ à¤¸à¥‡à¤µà¤¾ à¤®à¤¾à¤°à¥à¤—à¤¾à¤šà¥‡ à¤¹à¥‡ à¤…à¤§à¤¿à¤•à¥ƒà¤¤ à¤¡à¤¿à¤œà¤¿à¤Ÿà¤² à¤µà¥à¤¯à¤¾à¤¸à¤ªà¥€à¤  à¤†à¤¹à¥‡. à¤¸à¥‡à¤µà¥‡à¤•à¤°à¥€ à¤†à¤£à¤¿ à¤­à¤¾à¤µà¤¿à¤•à¤¾à¤‚à¤¨à¤¾ à¤¨à¤¿à¤¤à¥à¤¯à¤¸à¥‡à¤µà¤¾ à¤µ à¤¸à¥‡à¤µà¤¾ à¤•à¤¾à¤°à¥à¤¯à¤¾à¤¶à¥€ à¤œà¥‹à¤¡à¤£à¥‡ à¤¹à¤¾ à¤¯à¤¾à¤šà¤¾ à¤‰à¤¦à¥à¤¦à¥‡à¤¶ à¤†à¤¹à¥‡.</p></section>}
  <nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}><span>âŒ‚</span>à¤®à¥à¤–à¥à¤¯à¤ªà¥ƒà¤·à¥à¤ </button><button className={view==="nitya"?"active":""} onClick={()=>setView("nitya")}><span>à¥</span>à¤¨à¤¿à¤¤à¥à¤¯à¤¸à¥‡à¤µà¤¾</button><button onClick={()=>setOpen(true)}><span className="jap">à¤œà¤ª</span>à¤®à¤‚à¤¤à¥à¤°à¤œà¤ª</button><button className={view==="calendar"?"active":""} onClick={()=>setView("calendar")}><span>â–£</span>à¤¦à¤¿à¤¨à¤¦à¤°à¥à¤¶à¤¿à¤•à¤¾</button><button className={view==="about"?"active":""} onClick={()=>setView("about")}><span>â“˜</span>à¤®à¤¾à¤¹à¤¿à¤¤à¥€</button></nav>
  {open&&<div className="overlay" role="dialog" aria-modal="true"><div className="counterbox"><button className="close" onClick={()=>setOpen(false)}>Ã—</button><em>à¤¶à¥à¤°à¥€ à¤¸à¥à¤µà¤¾à¤®à¥€ à¤¸à¤®à¤°à¥à¤¥</em><h2>à¤®à¤‚à¤¤à¥à¤°à¤œà¤ª</h2><button className="counter" onClick={()=>setCount(count+1)}><b>{count}</b><small>à¤®à¥‹à¤œà¤£à¥à¤¯à¤¾à¤¸à¤¾à¤ à¥€ à¤¸à¥à¤ªà¤°à¥à¤¶ à¤•à¤°à¤¾</small></button><footer><button onClick={()=>setCount(0)}>à¤ªà¥à¤¨à¥à¤¹à¤¾ à¤¸à¥à¤°à¥‚ à¤•à¤°à¤¾</button><b>{Math.floor(count/108)} à¤®à¤¾à¤³à¤¾</b></footer></div></div>}
 </main>
}
