"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import type {Language} from "./translations";

type Knowledge={title:string;text:string;section:string;kind:string};
type ChatMessage={role:"user"|"assistant";text:string;results?:Knowledge[]};
const strip=(value:string)=>value.replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim();
const aliases:Record<string,string>={aarti:"आरती",arti:"आरती",charitra:"चरित्र",chapter:"अध्याय",adhyay:"अध्याय",nitya:"नित्यसेवा",seva:"सेवा",chanting:"मंत्रजप",mantra:"मंत्र",mala:"माळा",calendar:"पंचांग",panchang:"पंचांग",gurupeeth:"गुरुपीठ",swami:"स्वामी"};
const stop=new Set(["what","where","when","which","who","how","is","are","the","a","an","of","in","on","to","for","and","can","i","me","tell","about","काय","कसे","कसा","कशी","कोण","कुठे","कधी","आहे","आहेत","मला","बद्दल","ची","चा","चे","मध्ये","आणि","सांगा"]);
function tokens(value:string){return value.toLocaleLowerCase().replace(/[^\p{L}\p{N}\s]/gu," ").split(/\s+/).filter(x=>x.length>1&&!stop.has(x)).map(x=>aliases[x]||x)}
function excerpt(text:string,terms:string[]){const clean=strip(text);let at=-1;for(const term of terms){at=clean.toLocaleLowerCase().indexOf(term.toLocaleLowerCase());if(at>=0)break}const start=Math.max(0,(at<0?0:at)-90),end=Math.min(clean.length,start+430);return `${start?"…":""}${clean.slice(start,end).trim()}${end<clean.length?"…":""}`}
function search(question:string,docs:Knowledge[]){const terms=tokens(question),phrase=question.toLocaleLowerCase().trim();return docs.map(doc=>{const title=doc.title.toLocaleLowerCase(),text=doc.text.toLocaleLowerCase();let score=phrase&&title.includes(phrase)?30:0;for(const term of terms){if(title.includes(term))score+=12;if(text.includes(term))score+=3}return{doc,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>({...x.doc,text:excerpt(x.doc.text,terms)}))}
const builtIn:Knowledge[]=[
 {title:"स्वामी चरित्र सारामृत",text:"स्वामी चरित्र सारामृतामध्ये एकूण २१ अध्याय आहेत. प्रत्येक अध्याय वाचल्यानंतर प्रगती जतन करता येते आणि पूर्ण पारायणाची संख्या खात्यात दिसते.",section:"charitra",kind:"माहिती"},
 {title:"मंत्रजप आणि माळा",text:"मंत्रजप मोजण्यासाठी मंत्रजप विभागातील वर्तुळाला स्पर्श करा. १०८ जप म्हणजे एक माळा. जप जतन करा बटणाने मोजणी खात्यात जतन होते.",section:"jap",kind:"माहिती"},
 {title:"आजचे पंचांग",text:"स्वामी मार्गदर्शिका विभागात आजचे पंचांग आणि तारीख निवडण्याची सुविधा उपलब्ध आहे.",section:"calendar",kind:"माहिती"},
 {title:"आरती संग्रह",text:"आरती संग्रहामध्ये उपलब्ध सर्व आरत्या वाचता येतात. उघडलेल्या आरतीच्या शेवटी मागील आरती, आरती सूची आणि पुढील आरती बटणे आहेत.",section:"aarti",kind:"माहिती"},
 {title:"नित्यसेवा",text:"नित्यसेवा विभागात नित्यसेवा मंत्र, श्री स्वामी स्तवन, गणपती अथर्वशीर्ष आणि इतर स्तोत्र व मंत्र उपलब्ध आहेत.",section:"nitya",kind:"माहिती"}
];
export default function SiteAssistant({language,onOpenSection}:{language:Language;onOpenSection:(section:string)=>void}){
 const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[docs,setDocs]=useState<Knowledge[]>(builtIn),[input,setInput]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]);const messagesRef=useRef<HTMLDivElement>(null);
 const c=language==="mr"?{name:"श्री गुरुपीठ सहाय्यक",hello:"नमस्कार! आरती, नित्यसेवा, स्वामी चरित्र, मंत्रजप, पंचांग किंवा या संकेतस्थळावरील माहितीसंबंधी प्रश्न विचारा.",placeholder:"तुमचा प्रश्न येथे लिहा…",send:"पाठवा",close:"बंद करा",empty:"या प्रश्नाचे उत्तर संकेतस्थळावरील उपलब्ध माहितीत सापडले नाही. कृपया वेगळ्या शब्दांत प्रश्न विचारा.",source:"संबंधित माहिती",open:"विभाग उघडा",thinking:"माहिती शोधत आहे…",notice:"उत्तरे फक्त या संकेतस्थळावरील उपलब्ध मजकुरावर आधारित आहेत."}:{name:"Shri Gurupeeth Assistant",hello:"Namaskar! Ask about Aarti, Nitya Seva, Swami Charitra, mantra chanting, Panchang or information available on this website.",placeholder:"Type your question…",send:"Send",close:"Close",empty:"I could not find this answer in the available website information. Please ask using different words.",source:"Related information",open:"Open section",thinking:"Searching the website…",notice:"Answers are based only on content available on this website."};
 useEffect(()=>{if(!open||docs.length>builtIn.length)return;setLoading(true);Promise.all([fetch("/app-assets/aarti.json").then(r=>r.json()),fetch("/app-assets/nityasevastotramantra.json").then(r=>r.json()),fetch("/app-assets/newswamicharitra.json").then(r=>r.json())]).then(([aarti,nitya,charitra])=>{const next:Knowledge[]=[...builtIn];for(const group of aarti)for(const item of group.items||[])next.push({title:item.title,text:item.text||"",section:"aarti",kind:group.title||"आरती"});for(const item of nitya.resources?.string||[])next.push({title:item._name,text:item.__text||"",section:"nitya",kind:"नित्यसेवा"});for(const item of charitra.data||[])next.push({title:item.title,text:strip(item.description||""),section:"charitra",kind:"स्वामी चरित्र"});setDocs(next)}).catch(()=>{}).finally(()=>setLoading(false))},[open,docs.length]);
 useEffect(()=>{if(open&&messages.length===0)setMessages([{role:"assistant",text:c.hello}])},[open,messages.length,c.hello]);useEffect(()=>{const messageBox=messagesRef.current;if(messageBox)messageBox.scrollTo({top:messageBox.scrollHeight,behavior:"smooth"})},[messages,loading,open]);
 function ask(e:FormEvent){e.preventDefault();const question=input.trim();if(!question)return;const found=search(question,docs);setMessages(prev=>[...prev,{role:"user",text:question},{role:"assistant",text:found.length?found[0].text:c.empty,results:found}]);setInput("")}
 const suggestions=useMemo(()=>language==="mr"?["स्वामी चरित्रात किती अध्याय आहेत?","मंत्रजप कसा मोजायचा?","आरती संग्रह दाखवा"]:["How many Charitra chapters are there?","How do I count mantra chanting?","Show the Aarti collection"],[language]);
 return <><button className="assistant-launcher" onClick={()=>setOpen(true)} aria-label={c.name}><span>ॐ</span><b>{language==="mr"?"सहाय्य":"Help"}</b></button>{open&&<section className="assistant-panel" role="dialog" aria-modal="false" aria-label={c.name}><header><div><span>ॐ</span><div><b>{c.name}</b><small>{loading?c.thinking:"Online · No external AI"}</small></div></div><button onClick={()=>setOpen(false)} aria-label={c.close}>×</button></header><div className="assistant-messages" ref={messagesRef}>{messages.map((message,index)=><article className={message.role} key={index}><p>{message.text}</p>{message.results&&message.results.length>0&&<div className="assistant-results">{message.results.map((result,i)=><button key={`${result.title}-${i}`} onClick={()=>{onOpenSection(result.section);setOpen(false)}}><small>{result.kind}</small><b>{result.title}</b><span>{c.open} →</span></button>)}</div>}</article>)}{loading&&<article className="assistant-loading">{c.thinking}</article>}</div>{messages.length<=1&&<div className="assistant-suggestions">{suggestions.map(x=><button key={x} onClick={()=>setInput(x)}>{x}</button>)}</div>}<form onSubmit={ask}><input value={input} maxLength={240} onChange={e=>setInput(e.target.value)} placeholder={c.placeholder} aria-label={c.placeholder}/><button disabled={!input.trim()}>{c.send}</button></form><footer>{c.notice}</footer></section>}</>;
}
